"""Mein Kommentar zur anpassung 

Revision ID: 2ac6b2503e95
Revises: 86a9a20979e4
Create Date: 2023-09-01 12:06:04.051574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac6b2503e95'
down_revision = '86a9a20979e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inputTitle', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('inputPost', sa.String(length=10000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('inputPost')
        batch_op.drop_column('inputTitle')

    # ### end Alembic commands ###
